#!/usr/bin/env bash
# Configure HAProxy to redirect HTTP traffic to HTTPS

# Backup HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Update HAProxy configuration for HTTP to HTTPS redirection
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

frontend https-in
    bind *:443 ssl crt /etc/ssl/private/holberton.pem
    default_backend www-backend

backend www-backend
    server webserver1 10.0.0.2:80

EOF

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy

# Display HAProxy configuration for verification
cat /etc/haproxy/haproxy.cfg

