#!/usr/bin/env bash
# Debugging Nginx web server

# Ensure script runs with root privileges
if [[ $(id -u) -ne 0 ]]; then
    echo "Please run this script with sudo or as root."
    exit 1
fi

# Modify Nginx configuration to listen on port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

# Restart Nginx
nginx -s reload

# Kill Nginx workers to ensure configuration changes take effect
pkill -1 nginx

